name: Sync Repo A → Repo B

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Force push to Repo B
        run: |
          git push --force https://x-access-token:${{ secrets.REPO_B_TOKEN }}@github.com/showanime-4dx/Test.git HEAD:main
